code --install-extension asvetliakov.vscode-neovim
code --install-extension castwide.solargraph
code --install-extension circlecodesolution.ccs-flutter-color
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension esskar.vscode-flutter-i18n-json
code --install-extension hediet.vscode-drawio
code --install-extension HookyQR.beautify
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension Nash.awesome-flutter-snippets
code --install-extension rebornix.ruby
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wesbos.theme-cobalt2
code --install-extension wingrunr21.vscode-ruby
code --install-extension wmaurer.change-case
code --install-extension alexcvzz.vscode-sqlite
code --install-extension asvetliakov.vscode-neovim
code --install-extension bung87.rails
code --install-extension bung87.vscode-gemfile
code --install-extension castwide.solargraph
code --install-extension circlecodesolution.ccs-flutter-color
code --install-extension cssho.vscode-svgviewer
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension esskar.vscode-flutter-i18n-json
code --install-extension freebroccolo.reasonml
code --install-extension hediet.vscode-drawio
code --install-extension HookyQR.beautify
code --install-extension jcbuisson.vue
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension mathiasfrohlich.Kotlin
code --install-extension misogi.ruby-rubocop
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension Nash.awesome-flutter-snippets
code --install-extension rebornix.ruby
code --install-extension sianglim.slim
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wesbos.theme-cobalt2
code --install-extension wingrunr21.vscode-ruby
code --install-extension wmaurer.change-case
